import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        display: ['"Playfair Display"', '"Cormorant Garamond"', '"Iowan Old Style"', "serif"],
        serif: ['"Cormorant Garamond"', '"Iowan Old Style"', "Georgia", "serif"],
        sans: ["Inter", "Avenir Next", "Segoe UI", "system-ui", "sans-serif"],
        mono: ['"JetBrains Mono"', "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        status: {
          success: "hsl(var(--status-success))",
          "success-soft": "hsl(var(--status-success-soft))",
          warning: "hsl(var(--status-warning))",
          "warning-soft": "hsl(var(--status-warning-soft))",
          info: "hsl(var(--status-info))",
          "info-soft": "hsl(var(--status-info-soft))",
        },
        sera: {
          /* ── Brand primaries ── */
          navy:        "#071426",
          ink:         "#0D1B2E",
          oxblood:     "#5A1218",
          "oxblood-dk":"#3E0C11",
          cream:       "#F4EBDD",
          champagne:   "#E8D8C3",
          /* ── Brand secondaries ── */
          moss:        "#3D4A35",
          brass:       "#A9845C",
          rouge:       "#A35D5D",
          smoke:       "#A8B4C3",
          "soft-black":"#12100E",
          /* ── Tailwind-hsl tokens (pick up corrected CSS vars) ── */
          "deep-navy":  "hsl(var(--sera-deep-navy))",
          ivory:        "hsl(var(--sera-ivory))",
          beige:        "hsl(var(--sera-beige))",
          sand:         "hsl(var(--sera-sand))",
          stone:        "hsl(var(--sera-stone))",
          "warm-grey":  "hsl(var(--sera-warm-grey))",
          charcoal:     "hsl(var(--sera-charcoal))",
          "moss-muted": "hsl(var(--sera-moss-muted))",
          rosewood:     "hsl(var(--sera-rosewood))",
          "oxblood-soft":"hsl(var(--sera-oxblood-soft))",
          /* ── Legacy Atriae palette (kept for backward compat) ── */
          paper:        "#F7F2EC",
          blush:        "#E7D7D2",
          rose:         "#F1E7E4",
          matcha:       "#BED1BF",
          cloud:        "#FBF8F4",
          line:         "#D9D1C8",
          "ink-brown":  "hsl(var(--sera-ink-brown))",
          "ivory-paper":"hsl(var(--sera-ivory-paper))",
          "warm-stone": "hsl(var(--sera-warm-stone))",
          "surface-light": "hsl(var(--sera-surface-light))",
          "surface-warm":  "hsl(var(--sera-surface-warm))",
          "surface-cool":  "hsl(var(--sera-surface-cool))",
        },
      },
      borderRadius: {
        lg: "var(--radius-lg)",
        md: "var(--radius-md)",
        sm: "var(--radius-sm)",
        xl: "var(--radius-xl)",
        xl2: "24px",
        xl3: "32px",
        xl4: "36px",
        xl5: "40px",
      },
      spacing: {
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        8: "var(--space-8)",
        10: "var(--space-10)",
        12: "var(--space-12)",
        16: "var(--space-16)",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        soft: "var(--shadow-soft)",
        elevated: "var(--shadow-elevated)",
        glass: "var(--shadow-glass)",
        sera: "0 20px 60px rgba(36,31,28,0.08)",
        "sera-soft": "0 10px 30px rgba(36,31,28,0.05)",
        "card-dk": "0 24px 80px rgba(0,0,0,0.28)",
        "card-lt": "0 24px 70px rgba(7,20,38,0.12)",
      },
      letterSpacing: {
        display: "-0.05em",
      },
      backdropBlur: {
        sm: "var(--blur-sm)",
        md: "var(--blur-md)",
        lg: "var(--blur-lg)",
      },
      transitionDuration: {
        fast: "var(--motion-fast)",
        base: "var(--motion-base)",
        slow: "var(--motion-slow)",
      },
      transitionTimingFunction: {
        standard: "var(--ease-standard)",
        emphasized: "var(--ease-emphasized)",
        exit: "var(--ease-exit)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(16px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.6s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
